name: 'AWS Secrets Manager Github Action'
author: 'AWS Secrets Manager'
description: 'Retrieves AWS Secrets and allows them to be used as environment variables in Github workflows'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  secret-ids:
    description: 'One or more secret names, secret ARNs, or secret prefixes to retrieve'
    required: true
  parse-json-secrets:
    description: '(Optional) If true, JSON secrets will be deserialized, creating a secret environment variable for each key-value pair.'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/cleanup/index.js'
