name: 'AWS Secrets Manager GitHub Action'
author: 'AWS Secrets Manager'
description: 'GitHub action for retrieving secrets from AWS Secrets Manager'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  secret-ids:
    description: 'One or more secret names, secret ARNs, or secret prefixes to retrieve'
    required: true
  parse-json-secrets:
    description: '(Optional) If true, JSON secrets will be deserialized, creating a secret environment variable for each key-value pair.'
    required: false
    default: 'false'
  name-transformation:
    description: '(Optional) Transforms environment variable name. Options: uppercase, lowercase, none. Default value: uppercase.'
    required: false
    default: 'uppercase'
  auto-select-family-attempt-timeout:
    description: '(Optional) Sets the default value of the autoSelectFamilyAttemptTimeout option. Changing this value would change the length of timeout between each call to get a secret from  a select family. Use this option when some calls are taking longer than the default timeout'
    required: false
    type: number
    default: 1000
    minimum: 0
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/cleanup/index.js'
